import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik_80s_Fade } from "next/font/google";
import QueryProvider from "./providers/QueryProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const rubiksFade = Rubik_80s_Fade({
//   variable: "--font-rubik-80s-fade",
//   subsets: ["latin"],
//   weight: "400",
// });

export const metadata: Metadata = {
  title: "Game Stop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased bg-[#151515] text-white`}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
